#!/bin/bash

# If the projects directory or virtualenvs directory are not set,
# use sane defaults.
if [[ -z $PROJECTS_DIR ]]; then 
	PROJECTS_DIR=$HOME/gg
	mkdir -p $PROJECTS_DIR
fi

if [[ -z $VENVS_DIR ]]; then 
	VENVS_DIR=$HOME/venv
	mkdir -p $VENVS_DIR
fi


gg() {

	# Deactivate current virtualenv, if any
	deactivate 2> /dev/null
	if [[ ! -z $GG_OLD_PATH ]]; then 
		PATH=$GG_OLD_PATH
	fi

	if [[ ! -z $OLD_GOPATH ]]; then 
		GOPATH=$OLD_GOPATH
	fi


	# If there is no argument go to $PROJECTS_DIR, show some stuff, and leave
	if [[ $1 == "" ]]; then 
		cd $PROJECTS_DIR
		ls
		return
	# else if the argument is a git url clone it and go to it
	elif [[ $1 =~ 'http' || $1 =~ 'git@' || $1 =~ 'git://' ]]; then
		cd $PROJECTS_DIR
		# Run git clone and save messages on stdout and stderr
		CLONE_OUTPUT=$(git clone $1 $2 2>&1)

		# If the clone succeeded, find the directory created from the message
		# git wrote on stderr. Else, print git's problem and exit with its exit
		# code.
		if [[ $? == 0 ]]; then
			GIT_CLONE_DIR=$(echo $CLONE_OUTPUT |
				sed "s/^[^']*'//; s/'[^']*$//")
			cd $GIT_CLONE_DIR
		else
			echo clone_output
			exit $?
		fi
	# else if a directory in PROJECTS_DIR exists, go to it
	elif [[ -d $PROJECTS_DIR/$1 ]]; then 
		cd $PROJECTS_DIR/$1
	else
		echo "No project named" $1 "was found."
		return
	fi

	# If we successfully navigated to the directory, add it to our GOPATH, just
	# in case it's a Go repo.
	# FIXME: we should only do this if it's a go repo.
	OLD_GOPATH=$GOPATH
	GOPATH=$GOPATH:`pwd`

	# If there is a requirements.txt
	if [[ -e requirements.txt || -d requirements ]]; then
		__gg_source_venv
		if [[ $? == '0' ]]; then
			if [[ -e requirements.txt ]]; then
				pip install -r requirements.txt
			else 
				FILES=requirements/*
				for f in $FILES
				do
					pip install -r $f
				done
			fi
		fi
	elif [[ -e setup.py ]]; then
		__gg_source_venv
		if [[ $? == '0' ]]; then
			python setup.py install
		fi
	fi

	# If there is a package.json
	if [[ -e package.json ]]; then
		# If the node_modules directory exists, run npm install
		if [[ ! -e node_modules ]]; then
			npm install
		fi
		# Always path munge
		export GG_OLD_PATH=$PATH
		export PATH="$(pwd)/node_modules/.bin/:$PATH"
	fi
}

__gg_source_venv() {
	PROJ_NAME=${PWD##*/}
	# if a virtualenv exists source it, else create, install, and source it
	if [ -d "$VENVS_DIR/$PROJ_NAME" ]; then
		source $VENVS_DIR/$PROJ_NAME/bin/activate
		return 1;
	else 
		virtualenv $VENVS_DIR/$PROJ_NAME
		source $VENVS_DIR/$PROJ_NAME/bin/activate
		return 0;
	fi
}

__gg_autocomplete () {
	tmp=($(compgen -W "$(find "$PROJECTS_DIR"/* -maxdepth 0 | awk -F/ '{ print $NF }')" -- "${COMP_WORDS[$COMP_CWORD]}" ))
	COMPREPLY=( "${tmp[@]// /\ }" )
}

if [[ -z $GG_NO_AUTOCOMPLETE ]]; then
	complete -F __gg_autocomplete gg
fi
